### ISSUE TITLE
Restrict or filter auto responses to prevent bot spam

### ISSUE THREAD

**Issue by zacharyfleck** [TheFirePanel/TFPBot#195]
The bot currently has no method to prevent or limit responses to a message. This means that the bot will respond with pictures and emojis several times to the same message.

Potential solutions:
- Create some form of enabled/disabled channels for bot responses.
- Limit bot responses per message

**Comment by DrPepperG** [comment]
I agree with limiting the response due to the recent abuse, either we can
allow a set amount or just restrict it to the first match.

**Comment by zacharyfleck** [comment]
I'd vote for restricting to first match. It would be nice to be able to maintain a list of channel IDs we don't want it to respond in. Most are fine, but channels like announcements, moderated channels, mod chat, etc.. should probably have the ability to disable if possible.

**Comment by DrPepperG** [comment]
The config needs a slight overhaul to support list items, but for now I'll implement a first match instead of the current loop.
